server:
  host: "0.0.0.0"
  port: 9090

database:
  host: "localhost"
  port: 5432
  username: "user"
  password: "password"
  database: "mydb"

kafka:
  brokers:
    - "localhost:9093"
    - "localhost:9093"
  group_id: "my-group-updated"
  topic: "my-topic-updated"

redis:
  host: "redis-server"
  port: 6380
  password: "secret123"
  db: 1