server:
  host: localhost
  port: 8080
  protocol: http1

database:
  host: db.example.com
  port: 5432
  user: dbuser
  password: dbpassword
  dbname: myapp

logger:
  level: info
  format: json
  offset: last