server:
  host: localhost
  port: 9090
  #protocol: http

database:
  host: db.example.com
  port: 5432
  user: dbuser
  password: dbpassword
  dbname: myapp

logger:
  level: info
  format: json
  offset: last