# Configuration for plugin demo
kafka_producer:
  type: kafka
  bootstrap_servers: "localhost:9095"
  topic: "producer-topic"
  group_id: "producer-group"

kafka_consumer:
  type: kafka
  bootstrap_servers: "localhost:9093"
  topic: "consumer-topic"
  group_id: "consumer-group"

kafka_stream:
  type: kafka
  bootstrap_servers: "localhost:9094"
  topic: "stream-topic"
  group_id: "stream-group"

redis:
  type: redis
  host: "localhost"
  port: 6380
  password: ""
  db: 0
