server:
  host: "0.0.0.0"
  port: 9090

database:
  host: "localhost"
  port: 5432
  username: "user"
  password: "password"
  database: "mydb"

kafka:
  bootstrap_servers: "localhost:9090,localhost:9093"
  group_id: "my-group-updated"
  topic: "my-topic-updated"

redis:
  host: "redis-server"
  port: 6380
  password: "secret123"
  db: 1

kafka1:
  bootstrap_servers: "localhost:9092,localhost:9093"
  group_id: "my-group-updated"
  topic: "my-topic-updated"

client:
  kafka:
    bootstrap_servers: "localhost:9094,localhost:9095"
    group_id: "my-group-client"
    topic: "my-topic-client"
