# VCFG CLI Example Configuration

app:
  name: "VCFG-CLI-Example"
  version: "1.0.0"
  environment: "development"
  debug: true

server:
  host: "localhost"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"

database:
  url: "postgres://user:password@localhost:5432/mydb?sslmode=disable"
  max_conns: 25
  max_idle: 10
  max_lifetime: "1h"

logging:
  level: "info"
  format: "json"
  output: "stdout"
  file: "./logs/app.log"

# Plugin configuration
plugins:
  logger:
    type: "logger"
    level: "debug"
    format: "json"
    output: "both"
    file_path: "./logs/app.log"
    add_source: true
    enable_rotation: true
    rotate_interval: "daily"
    max_file_size: 104857600  # 100MB
    max_age: 7
